console.log("Hi :)");
var before="Divit";
console.log(before);
var after="Siddhant";
console.log(after);
var now=before.concat(after);
console.log(now);
var length=now.length;
console.log(length);
var low=now.toLowerCase();
console.log(low);
var up=now.toUpperCase();
console.log(up);
var sen="My Name Is Divit";
console.log(sen);
var ven=sen.replace("Divit","Siddhant");
console.log(ven);
var sq=Math.sqrt(225);
console.log(sq);
var max=Math.max(50,60);
console.log(max);
var min=Math.min(90000000000000000000,100000000000000000000000000);
console.log(min);
var pow=Math.pow(32,32);
console.log(pow);